services:
 mysql:
    image: mysql:8.0
    container_name: website-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ly@15984093508
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/data/mysql # 持久化存储数据库数据 命名卷，由docker进行管理的，默认放在 宿主主机的 /var/lib/docker/volumes/ 下

  app:
    image: registry.cn-hangzhou.aliyuncs.com/promonkeyli/website-go:latest
    container_name: website-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: website-nginx
    ports:
      - "8081:80" # 宿主8081 端口映射到 容器80 端口
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  mysql-data: # 命名卷 持久化数据
