services:
  mysql:
    image: mysql:8.0
    container_name: website-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ly@15984093508
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/data/mysql
    networks:
      - website-net

  app:
    image: registry.cn-hangzhou.aliyuncs.com/promonkeyli/website-go:latest
    container_name: website-app
    ports:
      - "8081:8081"
    environment:
      - GIN_MODE=release
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=ly@15984093508
      - DB_NAME=blog
    depends_on:
      - mysql
    networks:
      - website-net

  nginx:
    image: nginx:latest
    container_name: website-nginx
    ports:
      - "8080:8080" # 宿主8080 ==> 容器80 port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - website-net

volumes:
  mysql-data:

networks:
  website-net:
    driver: bridge
