services:
  app:
    image: registry.cn-hangzhou.aliyuncs.com/promonkeyli/website-go:latest
    container_name: website-app
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    networks:
      - website-net

  mysql:
    image: mysql:8.0
    container_name: website-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ly@15984093508
      MYSQL_DATABASE: blog
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/data/mysql
    networks:
      - website-net

  nginx:
    image: nginx:latest
    container_name: website-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - website-net

volumes:
  mysql-data:
networks:
  website-net:
    external: false  # 表示这是 Docker Compose 内部创建的网络，而不是外部已存在的网络
