definitions:
  model.Tool:
    description: Tool represents a tool entity
    properties:
      category:
        type: string
      name:
        type: string
      url:
        type: string
    type: object
info:
  contact: {}
paths:
  /tool/add:
    post:
      parameters:
      - description: Tool object to be added
        in: body
        name: tool
        required: true
        schema:
          $ref: '#/definitions/model.Tool'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Tool'
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 我的工具项新增
  /tool/list:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: 请求成功
          schema:
            $ref: '#/definitions/model.Tool'
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
      summary: 我的工具信息列表获取
swagger: "2.0"
