# GO Project build & deploy workflows
name: Deploy

on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用最新版本的 Ubuntu
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2 # 拉取代码

      - name: Build and push Docker image
        uses: docker/build-push-action@v2 # 构建和推送 Docker 镜像
        with:
          context: deployments # Dockerfile 所在的上下文路径, context在根目录
          push: true
          tags: username/repository:latest # 替换为你的 Docker 镜像标签
